export const GET_RECIPES = 'GET_RECIPES'
export const FILTER_BY_DIET = 'FILTER_BY_DIET'

export const SEARCH_RECIPE_BY_NAME = 'SEARCH_RECIPE_BY_NAME'

export const ORDER_RECIPE_ASC = 'ORDER_RECIPE_ASC'
export const ORDER_RECIPE_DESC = 'ORDER_RECIPE_DESC'

export const ORDER_SCORE_ASC = 'ORDER_SCORE_ASC'
export const ORDER_SCORE_DESC = 'ORDER_SCORE_DESC'

export const ADD_RECIPE = 'ADD_RECIPE'
