export const GET_RECIPES = 'GET_RECIPES'

export const GET_DIETS = 'GET_DIETS'

export const ORDER_RECIPE_BY_NAME = 'ORDER_RECIPE_NAME'
export const ORDER_RECIPE_BY_DIET = 'ORDER_RECIPE_SCORE'
export const ORDER_RECIPE_BY_SCORE = 'ORDER_RECIPE_SCORE'

export const SEARCH_RECIPE_BY_NAME = 'SEARCH_RECIPE_BY_NAME'

export const SEARCH_RECIPE_BY_ID = 'SEARCH_RECIPE_BY_ID'

export const ADD_RECIPE = 'ADD_RECIPE'
